name: Cypress Tests

on:
  push:
    branches:
      - main
      - qa
      - 'feature/**'  # Qualquer branch que comece com 'feature/'
  pull_request:
    branches:
      - main
      - qa
  repository_dispatch:
    types:
      - run-tests

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar Dependências
        run: |
          npm install

      - name: Executar Cypress (Home Test)
        run: |
          npm run test
