name: Cypress Tests

on:
  push:
    branches:
      - main
      - qa
      - 'feature/**'
  pull_request:
    branches:
      - main
      - qa
  repository_dispatch:
    types:
      - run-tests

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # Fazer checkout do código
      - name: Checkout do código
        uses: actions/checkout@v2

      # Instalar dependências do Cypress
      - name: Instalar Dependências
        run: |
          npm install

      # Executar os testes automatizados
      - name: Executar Cypress (Home Test)
        run: |
          npm run test

      # Disparar Pipeline de Merge no Projeto do Site
      - name: Disparar Pipeline de Merge
        if: success()  # Executa apenas se os testes passaram
        run: |
          echo "Disparando pipeline de merge no repositório do site"
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "User-Agent: demoblaze-automation" \
          https://api.github.com/repos/gersoncdias/demoblaze_site/dispatches \
          -d '{"event_type": "merge-triggered"}'
